import type { Tema } from "./tipos";

// Puntos de partida por estilo (los mismos que pregunta la plantilla de entrevista).
// El agente los ajusta con los colores reales del negocio.
export const ESTILOS: Record<string, Tema> = {
  deportivo: {
    nombreEstilo: "Deportivo",
    modo: "oscuro",
    colores: {
      primario: "#00e87a",
      textoSobrePrimario: "#050d07",
      fondo: "#080f0b",
      fondoAlterno: "#0d1a10",
      tarjeta: "#0f1f12",
      texto: "#f0f4f1",
      textoSuave: "#8aa88e",
      acento: "#ffd700",
    },
    fuentes: { titulos: "Bebas Neue", cuerpo: "Barlow" },
    titulosMayusculas: true,
    radio: 16,
    animaciones: "alta",
    fondoEfecto: "cuadricula",
    hero: "centrado",
    tarjetas: "elevadas",
  },
  elegante: {
    nombreEstilo: "Elegante",
    modo: "claro",
    colores: {
      primario: "#1c1c1c",
      textoSobrePrimario: "#ffffff",
      fondo: "#faf7f2",
      fondoAlterno: "#f1ece3",
      tarjeta: "#ffffff",
      texto: "#1c1c1c",
      textoSuave: "#6b645a",
      acento: "#b08d57",
    },
    fuentes: { titulos: "Playfair Display", cuerpo: "Lato" },
    titulosMayusculas: false,
    radio: 2,
    animaciones: "baja",
    fondoEfecto: "ninguno",
    hero: "dividido",
    tarjetas: "planas",
  },
  femenino: {
    nombreEstilo: "Femenino",
    modo: "claro",
    colores: {
      primario: "#c2627a",
      textoSobrePrimario: "#ffffff",
      fondo: "#fff8f8",
      fondoAlterno: "#fbeaec",
      tarjeta: "#ffffff",
      texto: "#3d2a30",
      textoSuave: "#8a6c74",
      acento: "#e8b4b8",
    },
    fuentes: { titulos: "Cormorant Garamond", cuerpo: "Nunito" },
    titulosMayusculas: false,
    radio: 22,
    animaciones: "media",
    fondoEfecto: "brillo",
    hero: "dividido",
    tarjetas: "elevadas",
  },
  minimalista: {
    nombreEstilo: "Minimalista",
    modo: "claro",
    colores: {
      primario: "#111111",
      textoSobrePrimario: "#ffffff",
      fondo: "#ffffff",
      fondoAlterno: "#f5f5f5",
      tarjeta: "#ffffff",
      texto: "#111111",
      textoSuave: "#666666",
      acento: "#111111",
    },
    fuentes: { titulos: "Inter", cuerpo: "Inter" },
    titulosMayusculas: false,
    radio: 6,
    animaciones: "baja",
    fondoEfecto: "ninguno",
    hero: "compacto",
    tarjetas: "borde",
  },
  juvenil: {
    nombreEstilo: "Juvenil",
    modo: "claro",
    colores: {
      primario: "#6c3cf0",
      textoSobrePrimario: "#ffffff",
      fondo: "#fffdf5",
      fondoAlterno: "#f3eeff",
      tarjeta: "#ffffff",
      texto: "#1d1534",
      textoSuave: "#5f5878",
      acento: "#ffcc00",
    },
    fuentes: { titulos: "Fredoka", cuerpo: "Poppins" },
    titulosMayusculas: false,
    radio: 24,
    animaciones: "alta",
    fondoEfecto: "puntos",
    hero: "centrado",
    tarjetas: "elevadas",
  },
  premium: {
    nombreEstilo: "Premium",
    modo: "oscuro",
    colores: {
      primario: "#d4af37",
      textoSobrePrimario: "#111111",
      fondo: "#0b0b0d",
      fondoAlterno: "#141418",
      tarjeta: "#17171c",
      texto: "#f4efe3",
      textoSuave: "#a59f90",
      acento: "#d4af37",
    },
    fuentes: { titulos: "Cinzel", cuerpo: "Montserrat" },
    titulosMayusculas: true,
    radio: 4,
    animaciones: "media",
    fondoEfecto: "brillo",
    hero: "dividido",
    tarjetas: "borde",
  },
  moderno: {
    nombreEstilo: "Moderno",
    modo: "claro",
    colores: {
      primario: "#2563eb",
      textoSobrePrimario: "#ffffff",
      fondo: "#f8fafc",
      fondoAlterno: "#eef2f7",
      tarjeta: "#ffffff",
      texto: "#0f172a",
      textoSuave: "#64748b",
      acento: "#f97316",
    },
    fuentes: { titulos: "Space Grotesk", cuerpo: "DM Sans" },
    titulosMayusculas: false,
    radio: 14,
    animaciones: "media",
    fondoEfecto: "cuadricula",
    hero: "dividido",
    tarjetas: "elevadas",
  },
};
